### ISSUE TITLE
anuga GUI setup

### ISSUE THREAD

**Issue by TejuJ** [GeoscienceAustralia/anuga_core#116]
Hello,
     I am trying to install anuga gui but I am not able to install plugin in qgis... which version of qgis support to anuga gui.
 I installed anuga through bash  and osgeo  qgis version  2.16.1  on windows.

**Comment by stoiver** [comment]
Hi TejuJ,


THe anuga gui was not developed or supported by us. You should check with the developers. It is probably not compatible with the current version of qgis. It is  fairly simple interface, just setting up the polygons defining the region to be triangulated.


But there are a number of ways to setup an anuga run.


I suggest you look in examples/cairn_excel directory to see a way to run a simulation by setting up an excel configuration file which specifies the simulation (usually specifies files defining polygons and lines). THese files can be created as shape files within qgis.


THen you can run the simulation maunally to produce an sww file, which can be read into qgis via the crayfish plugin.


Cheers

Steve


==============================
Stephen Roberts
Undergraduate Convenor
Mathematical Sciences Institute
Room 2005 P.A.P. Moran Building #26B
The Australian National University
Canberra, ACT 2601 AUSTRALIA
Ph: +61 2 61254445
CRICOS: 00120C

________________________________
