### ISSUE TITLE
Error installing ANUGA on Ubuntu

### ISSUE THREAD

**Issue by wlai2014** [GeoscienceAustralia/anuga_core#146]
Hi, 
I have an error in installing ANUGA on Ubuntu with 

bash tools/install_ubuntu.sh

Then after 
+=====================================================+
! Using pip to install netCDF4 
+=====================================================+

It shows:
"Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-dtwUKr/netCDF4"

Can anyone let we know what caused this? Thank you for your help.

**Comment by stoiveroberts** [comment]
@wlai2014, it seems there is a problem installing the python package netCDF4.

Try to install it manually. I.e. at the command line run the command

sudo pip install  netCDF4

and report on the outcome. 

By the way, which version of Ubuntu are you using?

**Comment by wlai2014** [comment]
@stoiveroberts
I am using Ubuntu 15.04 and my machine has two Python, Python 2.7 and Anaconda 3.5. So the sudo pip will use the Anaconda as default.  Need to change to Python 2.7 in order to install. 

Thanks.
