### ISSUE TITLE
Using ANUGA for Dam Break Studies

### ISSUE THREAD

**Issue by MrZogs** [GeoscienceAustralia/anuga_core#169]
Hi, 

I was wondering if is suitable for dam breach flooding modelling? If so, can you please share a dam breach case study or application using ANUGA? 

Thank you.

**Comment by ninnghazad** [comment]
If your problem is suitable to be solved using shallow water equations, then ANUGA should do the trick.
It comes with a set of examples which should be easily adaptable to your problem. 
Some python-knowledge may be needed.

**Comment by RudyFrom3** [comment]
Dam Breach can be undertaken in a few different ways.... Using real erosion approaches, or sudden catastrophic failure by using set_elevation for example (Which the erosion methods use in a smooth stepped approach). It is also Possible to use Riverwalls, and then remove the wall.... So it depends on your particular requirement...?

**Comment by phatwasin01** [comment]
> Dam Breach can be undertaken in a few different ways.... Using real erosion approaches, or sudden catastrophic failure by using set_elevation for example (Which the erosion methods use in a smooth stepped approach). It is also Possible to use Riverwalls, and then remove the wall.... So it depends on your particular requirement...?

How can I remove the riverwalls? 
Thanks

**Comment by RudyFrom3** [comment]
As mentioned there are a Number of ways to model a Dam Break, depending on your specific need.
If you want to model a Dam Break with a Reservoir Full at the Start of Simulation, and an immediate release, Simply set the Stage over the Reservoir Polygon! If you need to set a Specific Time of the Dam Break, the Set_Elevation can be used, or I understand the Riverwall Operator Height can be reset from its starting Value to Zero?  This will effectively remove the Riverwall. Check the RiverWall Code & Tests.... Alternatively you can Stop or Remove the Operator, which I guess would also remove the Riverwall, resulting in a Dam Break ? I will try set up a simple example...

**Comment by RudyFrom3** [comment]
So define a Riverwall: riverWall={'centralWall':[[25.5, 0.05, -1.50],[20.5, 4.950,0.5]]}   # Sloped Wall 
include the breakline in the Mesh Creation: anuga.create_mesh_from_regions(boundaryPolygon,
                             boundary_tags={'left': [0],
                                            'top': [1],
                                            'right': [2],
                                            'bottom': [3]},
                               maximum_triangle_area = 0.1,
                               minimum_triangle_angle = 28.0,
                               filename = 'rwall.msh',
                               interior_regions=interior_regions,
                               breaklines=riverWall.values(),
                               use_cache=False,
                               verbose=True)
Create the Riverwall Operator:  domain.riverwallData.create_riverwalls(riverWall)

Then in the Evolve loop at some point in time redefine the Riverwall with No Elevation
for t in domain.evolve(yieldstep=0.25, finaltime=26.0):
    print domain.timestepping_statistics()
    domain.print_timestepping_statistics()
    domain.report_water_volume_statistics()
    domain.print_operator_timestepping_statistics() 
    if t == 20.0:
        riverWall={'centralWall':[[25.5, 0.05, 0.0],[20.5, 4.95, 0.0]]}  # This resets the wall to Zero (Removes it !!)
