### ISSUE TITLE
Potential bug in Inlet_operator

### ISSUE THREAD

**Issue by ggiannako** [GeoscienceAustralia/anuga_core#225]
I have the impression that there is a minus sign missing when setting "applied_Q" in the case where we try to subtract a volume larger than the "current_volume":

self.applied_Q = **-** current_volume/timestep     instead of 
self.applied_Q = current_volume/timestep

This applies for both structures/inlet_operator.py (line 95) and parallel/parallel_inlet_operator.py (line 154). Can you please verify? 

Thank you.

**Comment by stoiver** [comment]
@ggiannako just committed changes as you suggested. THanks
