### ISSUE TITLE
anuga cannot generate .sww file

### ISSUE THREAD

**Issue by Passion-feng** [GeoscienceAustralia/anuga_core#230]
Hi, everyone:

@stoiver

First of all, I completed the "Install ANUGA on Windows using Gohlke Binaries" Anuga installation on Windows 10, and passed the unit test, which shows that my Anuga installation is correct. Afterwards, I ran the files in "\anuga_core\examples\simple_examples" (runup.py, channel1.py, channel2.py. etc.) using "Python IDLE" and "double-clicking" respectively. Generate .sww result file. Can you solve my problem?

Best regards
Passion-feng

**Comment by stoiver** [comment]
@Passion-feng I must admit I haven't tried the  "Install ANUGA on Windows using Gohlke Binaries" for quite a long time. I tend to use the miniconda installations. But if you were successful in getting the unit test to work then look like the installation worked. 

So are you saying that when running say channel1.py the output sww file name is ".sww".  That is strange. Can you explicitly run the command (in a cmd window)

python channel1.py

and see if you get the same problem. 

Once you have the channel1.sww file you can view the contents with the anuga_viewer (needs to be installed from github) or you can manually extract info via the plot_util commands.

**Comment by Passion-feng** [comment]
@stoiver Thank you very much! With your help, my problem is solved！
