### ISSUE TITLE
How to run anuga's .py script in parallel under windows 10

### ISSUE THREAD

**Issue by Passion-feng** [GeoscienceAustralia/anuga_core#235]
Hi, everyone:

@stoiver

I saw that the anuga homepage only has the parallel version of the Ubuntu platform, not the Windows platform. How do I parallelize the .py in Windows? Thank you!

**Comment by stoiver** [comment]
@Passion-feng  you can use `Miniconda` using the `conda-forge` channel to install `anuga` with `mpi4py`.

Essentially 
```
conda -c conda-forge install anuga, mpi4py
```
