### ISSUE TITLE
How do I generate rectangular mesh for irregular boundaries?

### ISSUE THREAD

**Issue by SaShaShady** [GeoscienceAustralia/anuga_core#241]
I have a set of points who are distanced from each other at regular intervals. I want to build a rectangular mesh for these points. 
I tried using the rectangular_cross_domain function but that provides me with a  boundary which is a complete rectangle.
The boundary which I want is irregular. To visualize, a set of small rectangles joining together. 
How can I accomplish my requirement? If not possible, is there any way I can remove the extra set of rectangles being formed in the mesh?

**Comment by stoiver** [comment]
@SaShaShady, I am unsure what you want to do. As you have observed, `rectangular_cross_domain`  sets up a rectangular domain with a "cross" triangular mesh. 

If you want to setup a more complicated domain, then you should use `create_domain_from_regions`. Have a look at notebooks 1 and 2 from the `anuga-clinic-2018` located at https://github.com/stoiver/anuga-clinic-2018 for how to use `create_domain_from_regions` to create a domain with a complicated boundary (notebook1) and interior regions of refinement (notebook2).

**Comment by SaShaShady** [comment]
Alright! Thank you so much. Will definitely have a look at it.
