### ISSUE TITLE
Looping hourly rainfall 

### ISSUE THREAD

**Issue by durerimon** [GeoscienceAustralia/anuga_core#253]
Hi, 
This CSV file (Precipitation_media_luna_24oct_7nov_20_ms-1.csv) below has two columns, containing hours (3600, 7200,......) and precipitation rate (0.000001,0,.......) in m/s. Now I would like to use this precipitation to the entire domain below. Any advice on how could I achieve this?

`
precipitation = scipy.genfromtxt(Deltapath +'/Model_Config/Precipitation_media_luna_24oct_7nov_20_ms-1.csv',delimiter=',',skip_header=0)   #m/s                                               #meters/second
rain_operator = Rate_operator(domain, rate = precipitation)

now = datetime.now()
print(('Starting Simulation at %s' %(now.strftime("%d/%m/%Y %H:%M:%S"))))
print(' SWW file will be: ' + scenario)# Evolve system through time

## Evolve system through time, yields output every * hour for a total of * days
for t in domain.evolve(yieldstep=Run_hour, duration=Run_day):                  #Run Hour = 1, Run day = 1
        domain.print_timestepping_statistics()
        if t%Run_hour == 0:
            dplotter.save_depth_frame(vmin = 0.0, vmax = 35.0,dpi = 200)
            dplotter.save_speed_frame(vmin = 0.0, vmax = 2.0,dpi = 200)
            dplotter.save_stage_frame(vmin = -0.5, vmax = 1.5,dpi = 200)
        if t > Run_day:
            rain_operator.set_rate(rate = 0.0)  
now = datetime.now()
print(('Completed Simulation at %s' %(now.strftime("%d/%m/%Y %H:%M:%S"))))

` 
- Thank you!

**Comment by stoiver** [comment]
@durerimon, I think you are pretty close. What you need to do is create a function which represents your rainfall. 

I would think something like the following should work. 

```
precipitation_data= scipy.genfromtxt(Deltapath +'/Model_Config/Precipitation_media_luna_24oct_7nov_20_ms-1.csv',delimiter=',',skip_header=0)   #m/s                                               #meters/second
from scipy import interpolate
precipitation_fun = interpolate.interp1d(precipitation[:,0], precipitation[[1,:])
rain_operator = Rate_operator(domain, rate = precipitation_fun)
```
Here I have assumed that your data file has 2 columns, with time in the first column and precipitation rate in the second column.

**Comment by durerimon** [comment]
-Thank you so much! It's running properly now.
