### ISSUE TITLE
Error running test_all.py when parallel environment not set

### ISSUE THREAD

**Issue by stoiver** [GeoscienceAustralia/anuga_core#26]
At present test_all.py will produce an error if parallel environnment has not been installed. Need to exclude the parallel directory from the test_all.py tests. Probably easiest to try to import pypar and if an exception then exclude the parallel directory from the tests.

**Comment by uniomni** [comment]
I thought we had a layer between ANUGA and pypar doing precisely that. From
memory it was called parallel.py

**Comment by stoiver** [comment]
Not really an issue with anuga or pypar. 

When we install anuga using setup.py, if pypar has not been installed, then it only installs the python files from parallel and doesn't try to compile the mpi_extras.c code or copy over the test files from parallel/tests. 

The runtests.py script runs fine in this case as it uses setup.py to setup a version of anuga to test and deals with htecase if pypar is not available.

But test_all.py is an older script, which just looks through the anuga_core/anuga/* directories for test_*.py files to run. And finds the parallel/tests files, tries to run them and then fails completely.

So one way to get test_all.py to work in this case is to change test_all.py to exclude the parallel directory if pypar is not available.
