### ISSUE TITLE
how to set initial flow and rain in mesh

### ISSUE THREAD

**Issue by janac4** [GeoscienceAustralia/anuga_core#260]
Hello everyone! I'm new in using ANUGA model for hydraulic simulation.
I work with WRF-Hydro to get streamflow evolution in a basin of 1300km2. I would like to use this runoff data as input flow (initial data or give the hidrogram evolution) in ANUGA model but I don't know how to do it.
Is set_quantity() function capable of it? I don't know which variables it accepts (aside from elevation and stage, but both are in meters and not streamflow - m3/s). 
All the example codes I found use initial stage=elevation (dry condition), but I couldn't find anaything close to my situation.
My idea is to impose specific evolution of flow in specific places of the basin (using hidrogram output of WRF-Hydro), but I could also use rainfall from WRF as input data . I'm not familliar with neither of these options.

**Comment by stoiver** [comment]
@janac4 sorry I didn't see your question until just now. 

I think the best way to implement the hidrograms is via Inlet_operators (which do take m^3/s functions of time as input. Checkout the doc page https://anuga.readthedocs.io/en/latest/examples/notebook_flooding_example.html and in particular the `setup inflow` section
