### ISSUE TITLE
Which repo/branch is for current python3 development?

### ISSUE THREAD

**Issue by beck-weber-ing** [GeoscienceAustralia/anuga_core#265]
Where should i PR for current python3 development?

**Comment by stoiver** [comment]
@beck-weber-ing, we try to keep the  main branch of  https://github.com/GeoscienceAustralia/anuga_core/ in sync with the main branch of https://github.com/anuga-community/anuga_core.  So the most recent version of `anuga_core` can be found in the repo https://github.com/anuga-community/anuga_core.
