### ISSUE TITLE
anuga erosion/deposition

### ISSUE THREAD

**Issue by mikilterribile** [GeoscienceAustralia/anuga_core#272]
Hi everyone,
I would like to add a simple erosion-operator, like for instance the exner equation, to my aunga simulation. I'm intersted in river and streams simulation. Is anuga-erosion suitable for this purpose? and how should I proceed? There is a user-manual of anuga-erosion I can read?
Thank you for your attention,
Best regards,
Michele Zucchelli.

**Comment by stoiver** [comment]
@mikilterribile thanks for the enquiry. 

There are some rudimentary erosion operators available in ANUGA, Sanddune_erosion_operator, Bed_shear_erosion_operator, Flat_slice_erosion_operator, Flat_fill_slice_erosion_operator. There are examples in `anuga_core/examples/operators`. These are essentially operators that scour but don't deposit.

There are at least 2 other projects. 

(1) ANUGA-erosion which you mentioned https://github.com/stoiver/ANUGA-erosion (my fork of the original created by Caleb I. Fassett)

(2) anugaSed: https://github.com/mperignon/anugaSed and https://github.com/mperignon/anuga-sedtransport which I have played with a bit. I think anugaSed is a little more up to date. 

I have a feeling that these two projects are related. 

Happy to work with you on setting up your own operator, but you might like to look at the options above to see if they meet your requirements. The two projects might not work out of the box with the latest version of ANUGA, so happy to help with that as well.

**Comment by stoiver** [comment]
@mikilterribile, It seems that ANUGA-erosion is more up to date than anugaSed. Also ANUGA-erosion has been used more recently for instance https://doi.org/10.1029/2021JE006979

**Comment by mikilterribile** [comment]
Stephen Roberts, thank you very much for your answers. I had already tryed to use anugased, but it wasn't working, bringing my simulations  to crash. So now I'm going to try with anuga-erosion. After a short look at your article, It seems to me that it uses the Exner equation or even better, computing both erosion and deposition. In order to simulate river and streams flooding events, I guess I should only use the suspended operator, with the Meyer-Peter_muller equation(?). Another question is about installation. Can I just copy the operators and the functions files in my anuga package? Thank you very much for your kindness and your time. Best regards, Michele Zucchelli.

**Comment by stoiver** [comment]
@mikilterribile I just had a quick look at ANUGA-erosion. It looks like the code works with the current version of anuga. Though the version at https://github.com/stoiver/ANUGA-erosion (branch main-py3) has been updated the print commands so that it works with python 3.

**Comment by mikilterribile** [comment]
I have tryied anuga-erosion and it works good. I just had to do a couple of changing for example to manage correctly the region.
I want to thanks you personally for developing this amazing tool. I only have a couple of questions:
1) why was solid density (Sd) set to 1650? The default number should be 2650 kg/m^3, so i ask wheter with "solid density" Sd - Sw is intended (the solid density minus the water density) even if the comment says "# Sediment Density   kg/m3"
2)I would like to use only the bedload transport operator. Does this operator include also the suspended transport, as it is if the Meyer-Peter-Muller formula is used?? Thank you very much for your kindness and your time. Best regards, Michele Zucchelli.

**Comment by stoiver** [comment]
@mikilterribile Good to hear you have had success with using ANUGA-erosion. Perhaps Caleb Fassett (@cfassett) might be interested in your success. (and maybe answer your questions))

But I'll try to answer your questions:

(1) Looking at the code, there are 3 examples, two using 3000 kg/m^3 and one using 1650. So I think it may be just a coincidence that your choice of value 2650 just happened to be 1650 + 1000. In the code the ratio of Sd/Wd is used which makes sense as the factor of sediment density to water. 

(2) Looking at the code, it looks like sediment transport is only calculated in the `suspendedtransport_operator`  So you should be able to run the various operators separately.

**Comment by mikilterribile** [comment]
Yes, let me a bit of time to improve and Chek my edits.
Michele

Il ven 19 apr 2024, 11:21 Stephen Roberts ***@***.***> ha
scritto:

**Comment by mikilterribile** [comment]
Ok, this morning I've work a bit on the bedloadtransport operator of anuga-erosion and I've noticed some unclear things (I don't know wheter are correct or uncorrect) and one that I thing is a real mistake. 
The mistake is in the Exner equation, it lacks the area term (1/cellarea): "dz=-(1/(1-porosity))*(self.gradX+self.gradY)*dt * 1/cellarea     #exner. #missing*1/cellarea???". Furthermore, i swear I dont understand the mass balancing, in my opinion they don't make any sense, but I'm not sure about. The following is my first attempt to create a similar operator, based on the Meyer-Peter-Muller formula, for an estimation both of the bedload transport and the suspended transport:                                                                                   "class bedloadtransport_operator(Operator, Region)  :
       
    def __init__(self,
                 domain,
                 indices=None,
                 polygon=None,
                 center=None,
                 radius=None,
                 description = None,
                 label = None,
                 logging = False,
                 verbose = False,
                 grainD = 0.0005,
                 rho_s = 2650,
                 theta_c = 0.05,
                 porosity = 0.4,
                 dthresh = 0.001,
                 maxrate = 5.0
                 ):
    

        Operator.__init__(self, domain, description, label, logging, verbose)

        Region.__init__(self, domain,
                        indices=indices,
                        polygon=polygon,
                        center=center,
                        radius=radius,
                        verbose=verbose)

            
        # set some alaises            
        self.stage = self.domain.quantities['stage'].centroid_values        
        self.depth = self.domain.quantities['height'].centroid_values
        self.elev = self.domain.quantities['elevation'].centroid_values
        self.xmom = self.domain.quantities['xmomentum'].centroid_values
        self.ymom = self.domain.quantities['ymomentum'].centroid_values

        self.grainD = grainD
        self.theta_c = theta_c
        self.rho_s = rho_s
        self.porosity = porosity

        self.dthresh = dthresh
        self.maxrate = maxrate




    def __call__(self):
        """
        Applies shear transport to those triangles defined in indices by the specified polygon
        indices == [], then don't apply anywhere
        otherwise apply for the specific indices within the erosion area polygon
        """
        
        updated = True             # flag called OK
        assert self.domain.get_using_discontinuous_elevation()  # make sure the model is allowing for discontinuous elevations at inner timesteps
        if len(self.indices) > 0:     # empty list no polygon - return  #codice originale: "if self.indices is not []:"
            dt = self.get_timestep()

            dthresh, maxrate = self.dthresh, self.maxrate
            maxdz    = maxrate*dt
            #-----------------------------------------------------------------------------------------
            # Compute erosion depths during the timestep and update centroid elevations accordingly 
			# Note this operator is called for each seperate erosion polygon.
            #-----------------------------------------------------------------------------------------
            
			#extract all the centroids in region with a minimum value of water depth
            ind = (self.depth >= dthresh) & np.isin(np.arange(len(self.depth)), self.indices)     #original code "(self.depth >= dthresh)"               # indices of triangles in polygon (where depth is above depth threshold: depth>dthresh)
            if len(ind)>0:
                height = self.stage_c[ind] - self.elev_c[ind]  #tiranti nella regione
                cellarea = self.areas[ind] #area delle celle nella regione
                depth = self.depth[ind]  #tiranti nella regione
                xmom = self.xmom[ind]  #quantità di moto x nella regione
                ymom  = self.ymom[ind] #quantità di moto y nella regione

                #calculating roughness, for each cell
                friction = self.domain.quantities["friction"][ind] #manning coefficient

                velx = xmom / (depth + 1.0e-8)  # component x of velocity
                vely = ymom / (depth + 1.0e-8)  # component y of velocity
                vel = np.sqrt(velx**2 + vely**2) #velocity module

                theta_c, rho_s, grainD, porosity = self.theta_c, self.rho_s, self.grainD, self.porosity
                rho = 1000 #water density
                g = 9.81 #gravity acceleration
                delta = (rho_s - rho)/rho  #1,65

                tau = rho * g / ((1/friction) ** 2 * depth ** (1 / 3)) * vel**2 #sforzo al fondo in modulo
                tau_x = rho * g / ((1/friction) ** 2 * depth ** (1 / 3)) * vel *  velx
                tau_y = rho * g / ((1/friction) ** 2 * depth ** (1 / 3)) * vel *  vely

                U_star = np.sqrt(tau / rho)
                theta = U_star ** 2 / (g * delta * grainD)
                Phi = np.where(theta >= theta_c, 8 * (theta - theta_c) ** (3 / 2), 0.0) #portata solida adimensionale, con meyer peter muller
                Phi = np.min(Phi, 400)  # per turanti tendenti allo zero, Phi tende a infinito e non ha senso dal punto di vista fisico
                qb_dim = Phi * grainD * np.sqrt(g * delta * grainD) #portata solida dimensionale [m^3/s]


                #calcola la portata solida nelle direzioni x e y, in base al rapporto tra gli sforzi di taglio
                qb_dim_x=np.zeros_like(self.depth)
                qb_dim_y=np.zeros_like(self.depth)
                qb_dim_x[ind]= qb_dim*(tau_x/(tau+1e-8))   # This method of partitioning the sediment flux
                qb_dim_y[ind]= qb_dim*(tau_y/(tau+1e-8))   # follows Gary Parker, eq. 2.12 (CISMnot2.pdf)

                #aggiora le variabili relative alla concentrazione del dominio
                # e sfrutta la funzione del dominio "compute gradients" per calcolare i gradienti
                self.domain.quantities['sedvolx'].set_values(qb_dim_x,location='centroids')  #These are quantities mostly for convenience (because it is useful to use the 
                self.domain.quantities['sedvoly'].set_values(qb_dim_y,location='centroids')  #ANUGA built in compute_gradients given the uneven mesh).
                self.sedxforgrad=self.domain.quantities['sedvolx']
                self.sedxforgrad.compute_gradients()
                self.sedyforgrad=self.domain.quantities['sedvoly']
                self.sedyforgrad.compute_gradients()
                self.gradX=self.sedxforgrad.x_gradient[ind]#prendo i gradienti solo nella regione [ind]
                self.gradY=self.sedyforgrad.y_gradient[ind]

                #noti i gradienti, calcola la variazione del fondo
                dz=-(1/(1-porosity))*(self.gradX+self.gradY)*dt * 1/cellarea     #exner. #manca *1/cellarea???


                #aggiorna il livello del fondo e il tirante nel dominio
                self.elev_c[ind] = self.elev_c[ind] + dz
                self.domain.set_quantity('elevation', self.elev_c, location='centroids')
                # Make sure stage is corrected once erosion happens to conserve fluid volume
                self.stage_c[ind] = self.elev_c[ind] + height
                self.domain.set_quantity('stage', self.stage_c, location='centroids')
                self.domain.distribute_to_vertices_and_edges()
 

        return (updated)      
              
        
    def parallel_safe(self):
        """If Operator is applied independently on each cell and
        so is parallel safe.
        """
        
        return True" The operator has not been tested yet, so probably it contains some errors and mistakes. In the next days I'll try to fix and improve it, when I find a bit of free time.  Best regards, Michele Zucchelli.

**Comment by stoiver** [comment]
@mikilterribile agree that I don't understand the mass balance. Surely it needs to keep track of flux across edges. Maybe the bedload transport is done in the sediment transport operator?

**Comment by mikilterribile** [comment]
Hello,

I think I might have been mistaken in dividing the Exner equation by 'cellarea,' as it led to unrealistically small erosion and deposition values. Conversely, not dividing by 'cellarea' seems to yield more reasonable results. This leads me to suspect that the 'compute_gradients' function might already be accounting for the 'cellarea' within its calculations. I would really like to verify this by checking the function, but I have been unable to find it in the ANUGA repository. Could you please help me locate it?

Best regards,

Michele Zucchelli

**Comment by stoiver** [comment]
@mikilterribile `compute_gradients` use the centroid values of the triangle and its 3 neighbouring triangle centroid values. Essentially a linear function (actually an affine function) is fitted to the 3 neighbouring centroid values and the gradient recovered from that linear function. It is a pointwise quantitiy. 

The actual location of the code is quite convoluted. `compute_gradients` is defined in `quantity.c` in the directory `abstract_2d_finite_volume`. This code is wrapped by the cython code `quantity_ext.pyx` which in turn gets integrated into anuga in the `quantity.py` file. Just to make it a bit more complicated, the actual gradient code is defined in the C code header file `util_ext.h` to be found in the `utilities` directory.

**Comment by mikilterribile** [comment]
Ok, yes I'm convinced that "*1/cellarea" is not correct, my mistake. This is the last version of my operator witch uses the Meyer-Peter-Muller formula for the solid transport estimation. This formula, for regular rivers/streams flooding event (not debris flows) does compute both the bedload transport and the suspended transport. If anybody wants to play with it: "
class bedloadtransport_operator(Operator, Region)  :
       
    def __init__(self,
                 domain,
                 indices=None,
                 polygon=None,
                 center=None,
                 radius=None,
                 description = None,
                 label = None,
                 logging = False,
                 verbose = False,
                 grainD = 0.0005,
                 rho_s = 2650,
                 theta_c = 0.05,
                 porosity = 0.4,
                 dthresh = 0.001,
                 maxrate = 5.0
                 ):
    

        Operator.__init__(self, domain, description, label, logging, verbose)

        Region.__init__(self, domain,
                        indices=indices,
                        polygon=polygon,
                        center=center,
                        radius=radius,
                        verbose=verbose)

            
        # set some alaises            
        self.stage = self.domain.quantities['stage'].centroid_values        
        self.depth = self.domain.quantities['height'].centroid_values
        self.elev = self.domain.quantities['elevation'].centroid_values
        self.xmom = self.domain.quantities['xmomentum'].centroid_values
        self.ymom = self.domain.quantities['ymomentum'].centroid_values

        self.grainD = grainD
        self.theta_c = theta_c
        self.rho_s = rho_s
        self.porosity = porosity

        self.dthresh = dthresh
        self.maxrate = maxrate


    def __call__(self):
        """
        Applies shear transport to those triangles defined in indices by the specified polygon
        indices == [], then don't apply anywhere
        otherwise apply for the specific indices within the erosion area polygon
        """
        
        updated = True             # flag called OK
        assert self.domain.get_using_discontinuous_elevation()  # make sure the model is allowing for discontinuous elevations at inner timesteps
        if len(self.indices) > 0:     # empty list no polygon - return  #codice originale: "if self.indices is not []:"
            dt = self.get_timestep()

            dthresh, maxrate = self.dthresh, self.maxrate
            maxdz    = maxrate*dt
            #-----------------------------------------------------------------------------------------
            # Compute erosion depths during the timestep and update centroid elevations accordingly 
			# Note this operator is called for each seperate erosion polygon.
            #-----------------------------------------------------------------------------------------
            
			#extract all the centroids in region with a minimum value of water depth
            ind = (self.depth >= dthresh) & np.isin(np.arange(len(self.depth)), self.indices)     #original code "(self.depth >= dthresh)"               # indices of triangles in polygon (where depth is above depth threshold: depth>dthresh)
            if len(ind)>0:
                height = self.stage_c[ind] - self.elev_c[ind]  #tiranti nella regione
                cellarea = self.areas[ind] #area delle celle nella regione
                depth = self.depth[ind]  #tiranti nella regione
                xmom = self.xmom[ind]  #quantità di moto x nella regione
                ymom  = self.ymom[ind] #quantità di moto y nella regione

                #calculating roughness, for each cell
                friction = self.domain.quantities['friction'].centroid_values[ind]

                velx = xmom / (depth + 1.0e-8)  # component x of velocity
                vely = ymom / (depth + 1.0e-8)  # component y of velocity
                vel = np.sqrt(velx**2 + vely**2) #velocity module

                theta_c, rho_s, grainD, porosity = self.theta_c, self.rho_s, self.grainD, self.porosity
                rho = 1000 #water density
                g = 9.81 #gravity acceleration
                delta = (rho_s - rho)/rho  #1,65

                tau = rho * g / ((1/friction) ** 2 * depth ** (1 / 3)) * vel**2 #sforzo al fondo in modulo
                tau_x = rho * g / ((1/friction) ** 2 * depth ** (1 / 3)) * vel *  velx
                tau_y = rho * g / ((1/friction) ** 2 * depth ** (1 / 3)) * vel *  vely

                U_star = np.sqrt(tau / rho)
                theta = U_star ** 2 / (g * delta * grainD)
                Phi = np.where(theta >= theta_c, 8 * (theta - theta_c) ** (3 / 2), 0.0) #portata solida adimensionale, con meyer peter muller
                Phi = np.minimum(Phi, 400)  # per turanti tendenti allo zero, Phi tende a infinito e non ha senso dal punto di vista fisico
                qb_dim = Phi * grainD * np.sqrt(g * delta * grainD) #portata solida dimensionale [m^3/s]

                #calcola la portata solida nelle direzioni x e y, in base al rapporto tra gli sforzi di taglio
                qb_dim_x=np.zeros_like(self.depth)
                qb_dim_y=np.zeros_like(self.depth)
                qb_dim_x[ind]= qb_dim*(tau_x/(tau+1e-8))   # This method of partitioning the sediment flux
                qb_dim_y[ind]= qb_dim*(tau_y/(tau+1e-8))   # follows Gary Parker, eq. 2.12 (CISMnot2.pdf)


                #aggiora le variabili relative alla concentrazione del dominio
                # e sfrutta la funzione del dominio "compute gradients" per calcolare i gradienti
                self.domain.quantities['sedvolx'].set_values(qb_dim_x,location='centroids')  #These are quantities mostly for convenience (because it is useful to use the 
                self.domain.quantities['sedvoly'].set_values(qb_dim_y,location='centroids')  #ANUGA built in compute_gradients given the uneven mesh).
                self.sedxforgrad=self.domain.quantities['sedvolx']
                self.sedxforgrad.compute_gradients()
                self.sedyforgrad=self.domain.quantities['sedvoly']
                self.sedyforgrad.compute_gradients()
                self.gradX=self.sedxforgrad.x_gradient[ind]#prendo i gradienti solo nella regione [ind]
                self.gradY=self.sedyforgrad.y_gradient[ind]

                #noti i gradienti, calcola la variazione del fondo
                dz=-(1/(1-porosity))*(self.gradX+self.gradY)*dt #    #exner

                #aggiorna il livello del fondo e il tirante nel dominio
                self.elev_c[ind] = self.elev_c[ind] + dz
                self.domain.set_quantity('elevation', self.elev_c, location='centroids')
                # Make sure stage is corrected once erosion happens to conserve fluid volume
                self.stage_c[ind] = self.elev_c[ind] + height
                self.domain.set_quantity('stage', self.stage_c, location='centroids')
                self.domain.distribute_to_vertices_and_edges()

        return (updated)      
              
        
    def parallel_safe(self):
        """If Operator is applied independently on each cell and
        so is parallel safe.
        """
        
        return True"
