### ISSUE TITLE
The anuga.Time_boundary() is removed with parallel model.

### ISSUE THREAD

**Issue by dzmjs** [GeoscienceAustralia/anuga_core#278]
I write a python script. When I run `python mpiRunDemo.py`, it is ok and the depth of domain can be changed.
However, in parallel model, `mpirun -n 2 python mpiRunDemo.py`, I find that the data of depth can NOT be changed. And I find that source code remove the Boundary.
`    def distribute(self, numprocs=1):

        self.numprocs = numprocs

        domain = self.domain
        verbose = self.verbose
        debug = self.debug
        parameters = self.parameters

        # FIXME: Dummy assignment (until boundaries are refactored to
        # be independent of domains until they are applied)
        bdmap = {}
        for tag in domain.get_boundary_tags():
            bdllmap[tag] = None`
      The MPI can NOT send Boundary Function.

**Comment by dzmjs** [comment]
Oh, The method is set_boundary({jsonkey: 'jsonVal'}) AGAIN!
 I validate the result, the data of depth of two kind of running types are same!

**Comment by stoiver** [comment]
@dzmjs looks like you found the problem. You need to set the boundary conditions via the `set_boundary` method AFTER distributing the original sequential domain created on processor 0 to the other processors. Checkout the examples in `anuga_core/examples/parallel`.

**Comment by dzmjs** [comment]
@stoiver Thank you, I had found the solution yesterday, and the result of depth can be changed. The model works well, thank you.
