### ISSUE TITLE
Zero depth in results

### ISSUE THREAD

**Issue by saberraz** [GeoscienceAustralia/anuga_core#3]
Currently, AnuGA outputs stage for every element in the model.Therefore, when you open the results in Crayfish, it shows all the domain as "wet".

Ideally, there should be a cut-off threshold, to stop dry areas being outputted in the SWW file.

**Comment by uniomni** [comment]
Stage is the elevation of the surface of the body of water and it has
nothing to do with what is wet or dry: That would be depth which is defined
as stage - elevation. It is generally up to the code that reads the SWW
file to decide the threshold for what is considered wet.

**Comment by stoiver** [comment]
Currently anuga users can set 

domain.set_minimum_storable_height()

The default value is 1.0e-3

So maybe we can setup cray-fish to consider all cells with less than 1.0e-3 depth as dry?

**Comment by saberraz** [comment]
It is done in Crayfish now. Other software do report stage in this manner so we added a threshold not to display the stage.
Thanks for your comments.
