### ISSUE TITLE
implement riverwalls with other solvers

### ISSUE THREAD

**Issue by pmilevski** [GeoscienceAustralia/anuga_core#30]
Is there any chance that riverwalls will be implemented with the over solvers, eg 1_5 solver? I want to run towradgi to see how it performs against DE0 and DE1.

**Comment by stoiver** [comment]
Hi Petar,

I actually think it might be difficult to implement riverwalls easily in the 1_5 solver. It would mean we have to implement a way to deal with discontinuities in the bed (along the edge) and that would mean essentially implementing DE_0 over the top of 1_5. 

Maybe Gareth might have a comment about how easy it would be to implement riverwalls with 1_5,  but I think it would be quite a task. 

Cheers
Steve

**Comment by gareth-d-ga** [comment]
Hi Petar and Steve,
Yes I agree with Steve -- it would be hard to do without discontinuous elevation.
Cheers,
Gareth

**Comment by pmilevski** [comment]
ok
