### ISSUE TITLE
friction issue

### ISSUE THREAD

**Issue by ilarsen** [GeoscienceAustralia/anuga_core#31]
When running the same code with different friction values, the velocity results are the same.

The script I am using to run ANUGA 1.3.10 follows and below that is a simplified version of the code I use to produce the output:

"""Script for running the flood simulation. Takes 5 command line 
arguments corresponding to the volume of water added to the system per second,
the time the simulation will run for, the resolutions of the outside area, the
resolution of the smaller polygon, and the output folder name.
"""

#------------------------------------------------------------------------------
# Import necessary modules
#------------------------------------------------------------------------------
import anuga 
import os #does file manipulation
import time
import sys #does command line arguments
import numpy 
import shutil #for copying the file

from anuga.structures.inlet_operator import Inlet_operator

#------------------------------------------------------------------------------
# Process command line arguments. Arguments are described above.
#------------------------------------------------------------------------------

try:
    in_vol = int(sys.argv[1])
    time = int(sys.argv[2])
    default_res = int(sys.argv[3])
    small_res = int(sys.argv[4])
    outfol = sys.argv[5]

except:
    print 'Incorrect command arguments for simluation. Arguments should be:\n\
    <InputVol> <FinalTime> <OutsideResolution> <FineResolution> <OutFolder>'
    sys.exit()

#------------------------------------------------------------------------------
# File Processing. If necessary, creates the output directory and copies the
# moses_gauges file to the new directory.
#------------------------------------------------------------------------------
root = 'moses' # variable will be name of all input and output variables
sww_file = root + '.sww' # name of the sww output file from previous segment
gauge_out = root + '_gauge_output.csv'   # name of the file to which depths will be written
gauge_in_file = root + '_gauges.csv'
ascii_file = root + '.asc'
dem_file = root + '.dem'
bnd_file = root+'_bnd.csv'
msh_file = root + '.tsh'
pts_file = root + '.pts'

if not os.path.exists(outfol):
    os.makedirs(outfol)
    shutil.copyfile(gauge_in_file, '%s/%s' %(outfol, gauge_in_file))

#------------------------------------------------------------------------------
# Preparation of topographic data
# Convert ASC 2 DEM 2 PTS using source data and store result in source data
#------------------------------------------------------------------------------

# Create DEM from asc data
anuga.asc2dem(ascii_file, use_cache=False, verbose=False) #ascii exported from dem in arcgis
# Create pts file for onshore DEM
anuga.dem2pts(dem_file, use_cache=True, verbose=False)

#------------------------------------------------------------------------------
# Create the triangular mesh and domain based on
# overall clipping polygon with a tagged
# boundary and interior regions as defined in project.py
#------------------------------------------------------------------------------

# bounding polygon for study area
bounding_polygon = anuga.read_polygon(bnd_file)
inner_poly = anuga.read_polygon('moses_inner_polygon_points.csv') #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Will have to change this line if want to add multiple regions or change inner region.
domain = anuga.create_domain_from_regions(bounding_polygon, boundary_tags={'s0':
            [0], 's1': [1], 'out1': [2], 'out2': [3], 'out3': [4], 's5': [5],
            's6': [6], 's7': [7], 's8': [8], 's9': [9], 's10': [10], 's11': 
            [11], 's12': [12], 's13': [13], 's14': [14], 's15': [15], 'in':
            [16], 's17': [17], 's18': [18], 's19': [19], 's20': [20], 's21':
            [21], 's22': [22], 's23': [23], 's24': [24], 's25': [25], 's26':
            [26], 's27': [27]},                            
        maximum_triangle_area = default_res, mesh_filename = msh_file,
        interior_regions = [[inner_poly, small_res]], use_cache = True,
        verbose = False) #s0 is name of the segment between the first two points in moses_bg_ply.csv, etc., the numbers assign each segment a number
    
# For multiple inner regions code should look like below:
'''
pol_1 = anuga.read_polygon('moses_pol_1.csv')
pol_2 = anuga.read_polygon('moses_pol_2.csv')
domain = anuga.create_domain_from_regions(bounding_polygon, boundary_tags={'s0':
            [0], 's1': [1], 'out1': [2], 'out2': [3], 'out3': [4], 's5': [5],
            's6': [6], 's7': [7], 's8': [8], 's9': [9], 's10': [10], 's11': 
            [11], 's12': [12], 's13': [13], 's14': [14], 's15': [15], 'in':
            [16], 's17': [17], 's18': [18], 's19': [19], 's20': [20], 's21':
            [21], 's22': [22], 's23': [23], 's24': [24], 's25': [25], 's26':
            [26], 's27': [27]},                            
        maximum_triangle_area = default_res, mesh_filename = msh_file,
        interior_regions = [[pol_1, small_res],[pol_2, small_res]], use_cache = True,
        verbose = False)
'''

# Print some stats about mesh and domain
print 'Number of triangles = ', len(domain)
print 'The extent is ', domain.get_extent()
print domain.statistics()

#------------------------------------------------------------------------------
# Setup parameters of computational domain
#------------------------------------------------------------------------------

domain.set_name(sww_file) # Name of sww file
domain.set_datadir('./%s/' %outfol) # changes directory to output folder
domain.set_minimum_storable_height(1) # writes data to sww file only if depth exceeds value (e.g., 1m); 
domain.set_minimum_allowed_height(1) #improves speed; see user manual

#------------------------------------------------------------------------------
# Setup initial conditions
#------------------------------------------------------------------------------

domain.set_quantity('stage', 0.0)
domain.set_quantity('friction', 0.035)
domain.set_quantity('elevation', filename=pts_file,
                    use_cache = True,
                    verbose  =False,
                    alpha  =0.1) #topographic smoothing; see user manual
    
line_in=[[298175.29404705,5279687.12514713], [300665.44798212,5279673.08820274]]
anuga.Inlet_operator(domain, line_in, in_vol)
# generates inlet operator from points
# to have an input operator polygon, just add additional pairs of points; last point connects to first point

#------------------------------------------------------------------------------
# Setup boundary conditions
#------------------------------------------------------------------------------

Br = anuga.Reflective_boundary(domain)
Bt = anuga.Transmissive_boundary(domain)
Bo = anuga.Dirichlet_boundary([-425, 0, 0]) #outflow.  Values of stage, x and y momentum.  The boundary will input of output water to attempt to get to the specified height. Negative stage is used to remove water and hopefully avoid numerical instability associated with transmissive boundary
domain.set_boundary({'s0':
            Br, 's1': Br, 'out1': Bo, 'out2': Bo, 'out3': Bo, 's5': Br, 's6':
            Br, 's7': Br, 's8': Br, 's9': Br, 's10': Br, 's11': Br,
            's12': Br, 's13': Br, 's14': Br, 's15': Br, 'in': Br,
            's17': Br, 's18': Br, 's19': Br, 's20': Br, 's21': Br,
            's22': Br, 's23': Br,'s24': Br, 's25': Br, 's26': Br, 's27': Br})

#------------------------------------------------------------------------------
# Evolve system through time
#------------------------------------------------------------------------------

# generates .sww file

#stage = domain.get_quantity('stage')
prev_dep=domain.get_quantity('stage').get_integral()
for t in domain.evolve(yieldstep=100, finaltime=time): #yieldstep is where timestep can be specified
    print domain.timestepping_statistics() #prints the timestep, time it took to run previous timestep, among other things
    cur_dep=domain.get_quantity('stage').get_integral()
    change = cur_dep - prev_dep
    prev_dep = cur_dep
    print 'time: %f, change: %f' %(t,change) #printed change value is change in water volume over 100 seconds

#*##############################################################################
# Gauge processing
#*##############################################################################

#------------------------------------------------------------------------------
# change working directory and create  and loop variables
#------------------------------------------------------------------------------

os.chdir('./%s/'%outfol) #changes the directory of the program to the output folder as specified in the command arguments
names=[]  #array used to hold the list of gauge sample names
output=[] #array used to hold all the depths over time
b=True    #boolean variable for loop manipulation

#------------------------------------------------------------------------------
# create the gauge files
#------------------------------------------------------------------------------

anuga.sww2csv_gauges(sww_file, gauge_in_file, quantities=['depth'], verbose=True)

#------------------------------------------------------------------------------
# combine all the gauge files into one output csv file
#------------------------------------------------------------------------------

with open(gauge_in_file,'r') as f: #opens the file that contains the list of gauge names and locations
    f.readline()
    for line in f: 
        line=line.split(',')
        oname='gauge_'+line[2]+'.csv'
        names.append(oname) #adds each gauge name to the array in order

for name in names: # this loop will run once for each name (and thus each gauge)
    if b: #this section will only execute the first run through
        b=False
        with open(name,'r') as cur_file:  #opens the corresponding gauge file
            cur = cur_file
            cur_file.readline()
            for line in cur_file:
                dep = line.split(',')[2].strip()
                output.append([float(dep)]) #processes the string into a useful format (a float in this case) and adds it to the array
    else: #this section will execute every run through except the first.  It functions the same except adding to each element of the array
        n=0
        with open(name,'r') as cur_file:
            cur_file.readline()
            for line in cur_file:
                dep = line.split(',')[2].strip()
                output[n].append(float(dep)) #processes each data point of the gauge file and adds it to the output
                n+=1
    os.remove(name) #this line deletes the gauge filesmade by the anuga method.  It's not necessary for functionality but makes the file directory cleaner
    
with open(gauge_out,'w') as out_file: #opens an output file and writes the output to the file. Note the output file is csv (comma seperated) and is usable in excel.
    for el in output:
        out_file.write(str(el).strip('[]'))
        out_file.write(' \n')        

print 'run complete'

#script used for processing output
import anuga

anuga.sww2dem('moses.sww', 'friction.asc', quantity='friction', cellsize=30,
                  reduction=20, verbose=True)

velocity = '(xmomentum**2 + ymomentum**2)**0.5/(stage-elevation+1.e-30)' #Velocity
anuga.sww2dem('moses.sww', 'velocity.asc', quantity=velocity, cellsize=30, reduction=20, verbose=True)

**Comment by stoiver** [comment]
Hi Isaac,

The code looks fine, so can't see why you would be having a problem. 

Would it be possible to provide the data files, in particular the asc file for the  elevation, and the polygon files for the domain. Maybe you can provide the data off line via dropbox?

Cheers
Steve

**Comment by stoiver** [comment]
Hi Isaac, 

The problem is with your command 

domain.set_minimum_allowed_height(1)

which converts any cell with less than 1m depth to be dry. This is the range over which the friction has its most important affect. So I would suggest removing that line, and you should then see different results for different friction values. 

Cheers
Steve

**Comment by ilarsen** [comment]
Hi Steve,
Thanks very much for trouble shooting this for me-much appreciated!
My initial tests indicate this indeed does make a substantial difference.

Cheers,
Isaac



Quoting Stephen Roberts <notifications@github.com>:
