### ISSUE TITLE
implement erosion and scour with other solvers and make parallel

### ISSUE THREAD

**Issue by pmilevski** [GeoscienceAustralia/anuga_core#33]
At the moment when modelling dam breaks or river bed scour I can only use the 1_5 solver in sequential mode.

Can erosion operator be made to work in parallel as well as with the default solver?

regards

**Comment by stoiver** [comment]
Hi Petar, 

In parallel mode and using the 1_5 algorithm, we need to transfer a complicated set of info to update the vertex values to ensure conservation of the scheme. 

With the discontinuous algorithms we only need to transfer centroid information and this is done automatically. 

So the erosion operator does work (or it should) in parallel mode. 

So I suggest you move to the DE_0 DE_1 algorithms. 

Cheers
Steve

**Comment by pmilevski** [comment]
Hi Steve, ok I'll move to the other solvers.

How can I read an external trimestep, elevation time series in the
flatslice/flat fill erosion operator?
