### ISSUE TITLE
Speedup Flather boundary condition

### ISSUE THREAD

**Issue by stoiver** [GeoscienceAustralia/anuga_core#91]
Boundary conditions can either be applied via an an 'evaluate' method then the boundary is applied using a loop in python (so is slow), whereas if we add an 'evaluate_segment' method then the application is vectorized, so it faster.

The Flather boundary condition has only the 'evaluate' method, and so is slow. 

We should implement the  'evaluate_segment' method for this BC as it is commonly used (eg in tsunami simulations).

**Comment by gareth-d-ga** [comment]
This is done now (also for transmissive_n_momentum_zero_t_momentum_set_stage). 
There are a couple of other boundary conditions there which could be similarly adjusted if we have a need for that.
